name = "PkgCacheInspector"
uuid = "a408fb95-4068-4cfa-a7f1-12fd503bd86c"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Colors", "Test"]
