name = "PkgCacheInspector"
uuid = "a408fb95-4068-4cfa-a7f1-12fd503bd86c"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
